FROM golang:1.14-stretch AS build-env

# Set up dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    make \
    git && \
    rm -rf /var/lib/apt/lists/*

# Set working directory for the build
WORKDIR /go/src/github.com/enigmampc/enigmablockchain

# Add source files
COPY . .

RUN go mod tidy

RUN make build_local_no_rust

# Final image
FROM ubuntu:18.04

# Install ca-certificates
WORKDIR /root

# Copy over binaries from the build-env
COPY --from=build-env /go/src/github.com/enigmampc/enigmablockchain/secretd /usr/bin/secretd
COPY --from=build-env  /go/src/github.com/enigmampc/enigmablockchain/secretcli /usr/bin/secretcli

COPY ./packaging_docker/chain_init.sh .
COPY ./packaging_docker/signed_swap_tx.json .

RUN chmod +x /usr/bin/secretd
RUN chmod +x /usr/bin/secretcli

# Run secretd by default, omit entrypoint to ease using container with secretcli
ENTRYPOINT ["/bin/bash", "chain_init.sh"]